apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        # 遇到 /api/ 開頭的網址，轉交給 Golang 總機
        location /api/ {
            proxy_pass http://backend-service:8080/;
        }

        # 其他所有的網址，轉交給 Next.js 前端總機
        location / {
            proxy_pass http://frontend-service:3000;
        }
    }